export const DataMaster = {
  id: 1,
  title: "NIK",
  label: "086512635661",
  children: [
    {
      id: 2,
      pid: 1,
      title: "Passport",
      title_group: "Passport",
      label: "8617671",
      id_group: 3,
      children: [
        {
          id: 4,
          pid: 2,
          id_group: 5,
          title: "Riwayat",
          title_group: "Riwayat",
          label: "Jakarta, Singapura",
          children: [],
        },
        {
          id: 6,
          pid: 2,
          id_group: 7,
          title: "Status",
          title_group: "Status",
          label: "Aktif",
          children: [],
        },
      ],
    },
    {
      id: 8,
      pid: 1,
      id_group: 9,
      title: "KK",
      title_group: "KK",
      label: "7162352",
      children: [
        {
          id: 10,
          pid: 8,
          id_group: 11,
          title: "Pajak",
          title_group: "Pajak",
          label: "0721637812",
          children: [
            {
              id: 16,
              pid: 10,
              id_group: 17,
              title: "Tagihan 1",
              title_group: "Tagihan",
              label: "100.000",
              children: [],
            },
            {
              id: 18,
              pid: 10,
              id_group: 17,
              title: "Tagihan 2",
              title_group: "Tagihan",
              label: "200.000",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 12,
      pid: 1,
      id_group: 13,
      title: "Phone",
      title_group: "Phone",
      label: "0812763",
      children: [],
    },
    {
      id: 14,
      pid: 1,
      id_group: 13,
      title: "Phone",
      title_group: "Phone",
      label: "8712656",
      children: [],
    },
    {
      id: 15,
      pid: 1,
      id_group: 13,
      title: "Phone",
      title_group: "Phone",
      label: "0612655",
      children: [],
    },
  ],
};

export const DataMasterRaw = [
  {
    id: 1,
    title: "NIK",
    label: "086512635661",
  },
  {
    id: 2,
    pid: 1,
    title: "Passport",
    title_group: "Passport",
    label: "8617671",
    id_group: 3,
  },
  {
    id: 4,
    pid: 2,
    id_group: 5,
    title: "Riwayat",
    title_group: "Riwayat",
    label: "Jakarta, Singapura",
    children: [],
  },
  {
    id: 6,
    pid: 2,
    id_group: 7,
    title: "Status",
    title_group: "Status",
    label: "Aktif",
    children: [],
  },
  {
    id: 8,
    pid: 1,
    id_group: 9,
    title: "KK",
    title_group: "KK",
    label: "7162352",
  },
  {
    id: 10,
    pid: 8,
    id_group: 11,
    title: "Pajak",
    title_group: "Pajak",
    label: "0721637812",
  },
  {
    id: 16,
    pid: 10,
    id_group: 17,
    title: "Tagihan 1",
    title_group: "Tagihan",
    label: "100.000",
  },
  {
    id: 18,
    pid: 10,
    id_group: 17,
    title: "Tagihan 2",
    title_group: "Tagihan",
    label: "200.000",
  },
  {
    id: 12,
    pid: 1,
    id_group: 13,
    title: "Phone",
    title_group: "Phone",
    label: "0812763",
  },
  {
    id: 14,
    pid: 1,
    id_group: 13,
    title: "Phone",
    title_group: "Phone",
    label: "8712656",
  },
  {
    id: 15,
    pid: 1,
    id_group: 13,
    title: "Phone",
    title_group: "Phone",
    label: "0612655",
  },
];
